### PR TITLE
refactor scenes to be created with shape

### PR DESCRIPTION
**Pull request by ahdinosaur**
current problem: i don't know how to own the current shape in the render loop, while also re-creating the scene manager when the shape changes.

```
error[E0506]: cannot assign to `shape` because it is borrowed
  --> src/render.rs:58:25
   |
35 |         let mut scene_manager = scene::SceneManager::new(&shape);
   |                                                           ----- borrow of `shape` occurs here
...
58 |                         shape = value;
   |                         ^^^^^^^^^^^^^ assignment to borrowed `shape` occurs here


```

@pietgeursen halp?

### CODE REVIEW

**Comment by pietgeursen** [comment]
Hmmm yeah.
Had a **quick** play with the code.

Here are some of my half thought out reckons:
- The adage of "share messages not memory" is what we should be going for. I think you're trying to share refs across multiple threads and that's sharing memory. Could this be redesigned to just pass messages?
- If we must pass a piece of data, can we do it by passing by value and just transferring ownership at the same time? I think that'd make it easy to draw a diagram of the value being passed to threads and see who owns it when.

**Comment by pietgeursen** [comment]
I guess I've been stuck fighting the compiler for ages trying to do something that just won't work because I don't understand something. 

If you can prove to yourself your ownership model is legal first, and then write the code, you are less likely to get stuck in a loop juggling things to try and make the compiler happy.

**Comment by ahdinosaur** [comment]
> The adage of "share messages not memory" is what we should be going for. I think you're trying to share refs across multiple threads and that's sharing memory. Could this be redesigned to just pass messages?

this is all within a single thread, sharing across threads has been easy so far.

i must have been unclear at the specific problem. currently the problem is scoped to the `SceneManager`'s relationship with `shape`. i'm trying to make it so the scene manager owns the shape and passes references to it's scenes. but for some reason this isn't working as expected.

```rust
pub struct SceneManager<'a> {
    shape: shape::Shape,
    scenes: Vec<Box<Scene<'a> + 'a>>,
    current_scene_index: usize
}

impl<'a> SceneManager<'a> {
    pub fn new(shape: shape::Shape) -> SceneManager<'a> {
        let scenes: Vec<Box<Scene>> = vec![
            Box::new(test::Test::new(&shape)),
            Box::new(rainbow::RainbowLine::new(&shape)),
            Box::new(rainbow::Rainbow::new(&shape))
        ];
        let scene_manager = SceneManager {
            shape,
            scenes,
            current_scene_index: 0
        };
        return scene_manager;
    }
}
```

```rust
            for render_message in next_render_messages {
                match render_message {
                    RenderMessage::Shape(value) => {
                        shape = value;
                        scene_manager = scene::SceneManager::new(shape.clone());
                        // ...
                    },
                   // ...
            }
```

```
error[E0597]: `shape` does not live long enough
  --> src/scene/mod.rs:30:45
   |
30 |             Box::new(rainbow::Rainbow::new(&shape)),
   |                                             ^^^^^ does not live long enough
...
43 |     }
   |     - borrowed value only lives until here
   |
note: borrowed value must be valid for the lifetime 'a as defined on the impl at 25:1...
  --> src/scene/mod.rs:25:1
   |
25 | / impl<'a> SceneManager<'a> {
26 | |     pub fn new(shape: shape::Shape) -> SceneManager<'a> {
27 | |         let scenes: Vec<Box<Scene>> = vec![
28 | |             Box::new(test::Test::new(&shape)),
...  |
69 | |     }
70 | | }
   | |_^
````

**Comment by ahdinosaur** [comment]
i figured it out, yay! thanks @pietgeursen for being a great [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging).

after mucking around some more, i decided to try (yet again) cloning the shape for each scene. what we missed before was a lifetime for the scene `&self`.

fixes this error message:

```
error[E0495]: cannot infer an appropriate lifetime for borrow expression due to conflicting requirements
  --> src/scene/rainbow.rs:52:21
   |
52 |         let shape = &self.shape;
   |                     ^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 51:5...
  --> src/scene/rainbow.rs:51:5
   |
51 | /     fn scene<'a> (&self, time: control::Time) -> color::Colors<'a> {
52 | |         let shape = &self.shape;
53 | |
54 | |         let dots = &shape.dots;
...  |
74 | |         return Box::new(colors);
75 | |     }
   | |_____^
note: ...so that reference does not outlive borrowed content
  --> src/scene/rainbow.rs:52:21
   |
52 |         let shape = &self.shape;
   |                     ^^^^^^^^^^^
note: but, the lifetime must be valid for the lifetime 'a as defined on the method body at 51:5...
  --> src/scene/rainbow.rs:51:5
   |
51 | /     fn scene<'a> (&self, time: control::Time) -> color::Colors<'a> {
52 | |         let shape = &self.shape;
53 | |
54 | |         let dots = &shape.dots;
...  |
74 | |         return Box::new(colors);
75 | |     }
   | |_____^
note: ...so that expression is assignable (expected std::boxed::Box<std::iter::Iterator<Item=color::Color> + 'a>, found std::boxed::Box<std::iter::Iterator<Item=color::Color>>)
  --> src/scene/rainbow.rs:74:16
   |
74 |         return Box::new(colors);
   |                ^^^^^^^^^^^^^^^^

error: aborting due to previous error
````

then, since i had already seen how using [`Rc`](https://static.rust-lang.org/doc/master/std/rc/index.html) was having the same error message as cloning, i decided to use `Rc` to keep the same semantics as cloning but without duplicating the data in memory.

:tada:

**Pull request merged**
